### ISSUE TITLE
Failing to get token

### ISSUE THREAD

**Issue by plumbweb-thad** [bggardner/simplisafe-proxy#1]
Hello!

I'm not sure if you're working on this project any more, but I noticed that in the last couple of days I started receiving server 500 errors due to a bad token being retrieved when trying to retrieve or assign states. I'm curious if the API base URL changed or maybe some other structural changes to their API?

**Comment by bggardner** [comment]
Looks like SimpliSafe changed their authentication process again and now uses Auth0.  I'll take a crack at it.

**Comment by plumbweb-thad** [comment]
Awesome, thanks so much! This code has been a lifesaver as the SimpliSafe hardware is affordable and easy to set up, but finding that along with an accessible API to integrate into a custom smart home is tough!

Out of curiosity, how have you been able to track down SimpliSafe's API endpoints?

**Comment by bggardner** [comment]
The [Python repo](https://github.com/bachya/simplisafe-python) has, which I've been using as a reference.

**Comment by bggardner** [comment]
I got it to work, though sometimes there is strange behavior during the API calls.  The Python repo performs automatic retries, but I didn't get to that.  Please post any relevant issues with the latest update in this thread.

**Comment by plumbweb-thad** [comment]
Ah shoot, it looks like something may have changed again on SimpliSafe's end. If you're still supporting this are you seeing an issue as well? Thank you for your insight!

**Comment by plumbweb-thad** [comment]
Sorry, disregard this. I think the API may have been down for a day or two, but it appears to have started working again.
